version: '3'

services:

  node-js-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=production
    working_dir: /usr/src/app
    command: [ "node", "app.js" ]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-js-app
